#'Calculates the three year average for the PM2.5 24 hour metric
#'
#'Flags if based on only two years.
#'
#'@import dplyr
#'@param  data data frame containing annual 98th percentile values, most likely 
#'  generated by \code{\link{pm_98_percentile}}
#'@param  yearcol name of the column containing the year
#'@param  valcol name of the column containing annual 98th percentile values
#'@param flag name of the column containing a flag (\code{TRUE/FALSE}) if the
#'  value in the given year is based on incomplete data (but is still ok to use).
#'@param  by character vector of grouping variables in data, probably an id if using multiple 
#'  sites. Even if not using multiple sites, you shoud specfify the id column so
#'  that it is retained in the output.
#'@param  year The year to calculate the metric for (this will be the latest of 
#'  the three years used in the calculation). Can be "latest" to use the latest 
#'  year found in the data frame, or an integer denoting the year.
#'@export
#'@seealso \code{\link{pm_98_percentile}}
#'@return a data frame, with year, the value, and the number of years the value 
#'  is based on
#' @examples \dontrun{
#' 
#'}
pm_24hr_caaq <- function(data, yearcol, valcol, flag, by = NULL, year = "latest") {
  vars <- c(yearcol, valcol, flag, by)
  
  for (var in vars) {
    if (!var %in% names(data)) stop(var, " is not a column in data")
  }
  
  if (inherits(year, c("integer", "numeric"))) {
    if (!year %in% data[[yearcol]]) stop(year, " does not exist in data")
  } else if (year == "latest") {
    year <- max(data[[yearcol]])
  } else {
    stop("year must be an integer or 'latest'")
  }
  
  if (!inherits(data[[valcol]], "numeric")) stop(valcol, "is not numeric")
  if (!inherits(data[[flag]], "logical")) stop("flag must be logical")
  
  years <- seq(to = year, length.out = 3)
  
  rows <- data[data[[yearcol]] %in% years & !is.na(data[[valcol]]), , drop = FALSE]
  
  if (is.null(by)) {
    if (any(duplicated(rows[[yearcol]]))) stop("duplicate values in ", yearcol, 
                                               " but no grouping variable(s) specified")
  } else {
    rows <- group_by_(rows, .dots = by)
  }
  
  caaq_formula <- interp(~ifelse(n_years >=2, round(mean(x), 1), NA_real_), 
                         x = as.name(valcol))
  
  ret <- summarise_(rows, 
                    caaq_year    = year,
                    min_year     = interp(~min(x), x = as.name(yearcol)),
                    max_year     = interp(~max(x), x = as.name(yearcol)),
                    n_years      = ~n(),
                    pm_24hr_caaq = caaq_formula, 
                    based_on_incomplete = interp(~any(x), x = as.name(flag)))
  ret
  
}
