#' Calculate the annual CAAQS metric for PM2.5
#'
#'@param  data data frame containing annual average values, most likely 
#'  generated by \code{\link{pm_annual_average}}
#'@param  yearcol name of the column containing the year
#'@param  valcol name of the column containing annual average values
#'@param  by character vector of grouping variables in data, probably an id if using multiple 
#'  sites. Even if not using multiple sites, you shoud specfify the id column so
#'  that it is retained in the output.
#'@param  year The year to calculate the metric for (this will be the latest of 
#'  the three years used in the calculation). Can be "latest" to use the latest 
#'  year found in the data frame, or an integer denoting the year.
#'
#' @return A data frame
#' @export
#'
pm_annual_caaq <- function(data, yearcol, valcol, by = NULL, year = "latest") {
  vars <- c(yearcol, valcol, by)
  
  for (var in vars) {
    if (!var %in% names(data)) stop(var, " is not a column in data")
  }
  
  if (inherits(year, c("integer", "numeric"))) {
    if (!year %in% data[[yearcol]]) stop(year, " does not exist in data")
  } else if (year == "latest") {
    year <- max(data[[yearcol]])
  } else {
    stop("year must be an integer or 'latest'")
  }
  
  if (!inherits(data[[valcol]], "numeric")) stop(valcol, "is not numeric")

  years <- seq(to = year, length.out = 3)
  
  rows <- data[data[[yearcol]] %in% years & !is.na(data[[valcol]]), , drop = FALSE]
  
  if (is.null(by)) {
    if (any(duplicated(rows[[yearcol]]))) stop("duplicate values in ", yearcol, 
                                               " but no grouping variable(s) specified")
  } else {
    rows <- group_by_(rows, .dots = by)
  }
  
  caaq_formula <- interp(~ifelse(n_years >=2, round(mean(x), 1), NA_real_), 
                         x = as.name(valcol))
  
  ret <- summarise_(rows, 
                    caaq_year    = year,
                    min_year     = interp(~min(x), x = as.name(yearcol)),
                    max_year     = interp(~max(x), x = as.name(yearcol)),
                    n_years      = ~n(),
                    pm_annual_metric = caaq_formula)
  ret
}
